name: model_training
on:
  push:

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Train model
        run: src/train.py
      - name: Upload trained model
        uses: actions/artifact@v3
        with:
          name: baummethoden_lr.pickle
          path: data/models/baummethoden_lr.pickle

